manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: jcmkk3
      url-base: https://github.com/jcmkk3
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: zmk-keyboard-berylline
      remote: jcmkk3
      revision: main
  self:
    path: config